### DISCUSSION TITLE
Advise needed.

### DISCUSSION THREAD

**Discussion by oywino** [sleevezipper/hass-workstation-service#44] [Q&A] [answered]
I'm looking for a way to trigger an automation only at the very first user activity on a windows machine between 07:15 am and 08:00 am daily. I have a feeling I could use the LastActive Sensor, but I'm not sure how.
Any help is appreciated.

**Comment by sleevezipper** [comment]
Hi! The LastActive sensor is going to change a little bit as it isn't being parsed as point in time correctly. Next release should be later today and that is going to make your use case a lot easier.

**Comment by oywino** [comment]
Great!  Can you suggest how you would write up such a trigger ?

**Reply by sleevezipper** [reply]
I think you'd be better off with the [SessionState sensor](https://github.com/sleevezipper/hass-workstation-service#sessionstate). This'll change to `InUse` when you sign in. Would that work for you?

**Reply by oywino** [reply]
I dont' think so, because this Windows Workstation is signed (logged in) 24/7.

**Reply by sleevezipper** [reply]
Ah I see. That's a tricky one! I'm not really sure how to do that. I'll ask around.

**Reply by Hankanman** [reply]
Okay I needed a binary sensor for if the pc was active.

First you need a last active sensor from Hass Workstation (sensor.last_active in this example)

Then I have two custom template sensors:

Minutes since last active:
`- platform: template
  sensors:
    time_since_last_active:
      unit_of_measurement: Minutes
      value_template: "{{ (states('sensor.date_time_iso') | as_timestamp  / 60) | round(0, 'floor') - (states('sensor.last_active') | as_timestamp / 60) | round(0, 'floor') }}"`

Then us that sensor to see if someone used the pc in the last 5 minutes as a binary sensor:
`- platform: template
    pc_active:
      friendly_name: "PC Active"
      device_class: presence
      value_template: >-
        {{ states('sensor.time_since_last_active') | int < 5 }}`

**Reply by Hankanman** [reply]
![Screenshot_20210317-221207](https://user-images.githubusercontent.com/3953290/111545418-f5cd7580-876d-11eb-9099-f4bd966c3d27.jpg)

![Screenshot_20210317-221055](https://user-images.githubusercontent.com/3953290/111545446-fd8d1a00-876d-11eb-951d-b1fefecafc4a.jpg)

**Reply by Hankanman** [reply]
Sorry code is formatted a bit weird, on mobile right now 
binary sensor syntax: [Binary Sensor Template](https://www.home-assistant.io/integrations/binary_sensor.template/) 
Template sensor syntax: [Template Sensor](https://www.home-assistant.io/integrations/template/) 

You can use the binary sensor to trigger the automation with a condition in the automation for the specific time you want so should be what you need!

**Reply by sleevezipper** [reply]
Oh that's a nifty template sensor.

**Comment by oywino** [comment, marked as answer]
This is how I solved it:

```
alias: Daily Action
description: ' '
trigger:
  - platform: state
    entity_id: sensor.lastactive
condition:
  - condition: template
    value_template: >-
      {% if as_timestamp(states.sensor.lastactive.last_changed) |
      timestamp_custom('%H') == '07' %}true{% else %}false{% endif %}
action:
  - service: switch.turn_on
    target:
      entity_id: switch.action
  - delay:
      hours: 0
      minutes: 60
      seconds: 0
      milliseconds: 0
mode: single
```
The above automation will only trigger once within the 7th hour of each day.
